# Perceptron

In [18]:
import numpy as np

# perceptron
def AND(x1, x2):
    W = np.array([0.5, 0.5])
    X = np.array([x1, x2])
    b = -0.7
    tmp = np.sum(W*X) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
def NAND(x1, x2):
    W = np.array([-0.5, -0.5]) # AND 게이트와 가중치(w, b)만 다름
    X = np.array([x1, x2])
    b = 0.7
    tmp = np.sum(W*X) + b
    if tmp <= 0:
        return 0
    else:
        return 1
        
def OR(x1, x2):
    W = np.array([0.5, 0.5]) # AND 게이트와 가중치(w, b)만 다름
    X = np.array([x1, x2])
    b = -0.2
    tmp = np.sum(W*X) + b
    if tmp <= 0:
        return 0
    else:
        return 1
        
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y
    

In [19]:
print(XOR(1, 0))
print(OR(1, 0))
print(AND(1, 0))
print(NAND(1, 0))

1
1
0
1


# Activation function

In [20]:
def step_function(x):
    y = x > 0
    return y.astype(np.int32)

In [50]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [22]:
def softmax(x):
    const = np.max(x)
    exp_a = np.exp(x-const)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [23]:
def relu(x):
    y = np.maximum(0, x)
    return y

In [24]:
test = np.random.randn(2, 2)
print("step function: \n", step_function(test))
print("sigmoid: \n", sigmoid(test))
print("relu: \n", relu(test))
print("softmax:", softmax(test))

step function: 
 [[1 0]
 [1 1]]
sigmoid: 
 [[0.92619234 0.16916576]
 [0.54690568 0.86286704]]
relu: 
 [[2.52961941 0.        ]
 [0.18817603 1.83930963]]
softmax: [[0.61964206 0.01005401]
 [0.05960257 0.31070137]]


# Neural Network

In [25]:
def init_network():
    network = {}
    network['W1'] = np.random.randn(2, 2)
    network['b1'] = np.random.randn(2, 2)
    network['W2'] = np.random.randn(2, 2)
    network['b2'] = np.random.randn(2, 2)
    network['W3'] = np.random.randn(2, 2)
    network['b3'] = np.random.randn(2, 2)
    
    return network

def forward(network, x, activation):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    l1 = np.dot(x, W1) + b1
    z1 = activation(l1)
    l2 = np.dot(z1, W2) + b2
    z2 = activation(l2)
    l3 = np.dot(z2, W3) + b3
    z3 = activation(l3)

    return z3

In [26]:
network_test = init_network()
test_result = forward(network_test, test, sigmoid)
print(test_result)


[[0.69047493 0.85802048]
 [0.26403635 0.12270176]]


In [27]:
test_result = forward(network_test, test, softmax)
print(test_result)

[[0.3838867  0.55066181]
 [0.05371374 0.01173775]]


# MNIST tuto

## load data

In [42]:
import sys, os
sys.path.append("C\:\\Users\\JEJOON YOO\\Desktop\\prgm\\밑시딥\\dataset")
from mnist import load_mnist

In [43]:
(x_train, y_train), (x_test, y_test) = load_mnist(flatten=True, normalize=True)

In [44]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


## inference tutorial

In [68]:
import pickle

def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(flatten=True, normalize=True, one_hot_label=False)
    return x_test, t_test

def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
    return network

def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b1'], network['b1']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2.T, W3) + b3
    y = softmax(a3)
    
    return y


In [67]:
x, t = get_data()
network = init_network()

acc_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p  = np.argmax(y)
    if p == t[i]:
        acc_cnt += 1

print("Acc:" + str(float(acc_cnt) / len(x)))

ValueError: operands could not be broadcast together with shapes (100,) (50,) 